### ISSUE TITLE
fix: Ensure storage is upgrade-safe

### ISSUE THREAD

**Issue by anna-carroll** [celo-org/optics-monorepo#121]
[EIP-1167](https://eips.ethereum.org/EIPS/eip-1167): Minimal Proxy Contract 
[Example contract](https://github.com/harvest-finance/harvest/blob/bae8b4abc69e9d993b3d13cb2f9016381b27b88f/contracts/strategies/upgradability/BaseUpgradeableStrategyStorage.sol): `BaseUpgradeableStrategyStorage.sol`

- [ ] Home
- [ ] Replica
- [ ] Governance xApp

**Comment by prestwich** [comment]
Thinking about this more. It seems the appropriate thing to do at this time is add a `bytes32[50] private __PADDING;` to each contract that will be inherited from. This ensures that we can later reconcile storage slots.

Reasoning to choose this over EIP-1967 style known-slot storage
1. Less boilerplate. By a lot.
2. Less refactoring. By a lot.
3. Consistent with the [openzeppelin contracts we already use](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/governance/GovernorUpgradeable.sol#L365)

**Comment by prestwich** [comment]
Steps:
1. make a list of everything that we deploy as a Beacon proxy.
2. Count the number of storage slots in each one
3. Add a `private uint256[X] __GAP;` to each pf those contracts

**Comment by prestwich** [comment]
closed by #566
