### ISSUE TITLE
how do we provision Ethereum and Celo nodes for the rust agents

### ISSUE THREAD

**Issue by anna-carroll** [celo-org/optics-monorepo#188]

**Comment by yourbuddyconner** [comment]
Created GCP Project, working on implementing action plan in Terraform.

**Comment by yourbuddyconner** [comment]
Looking at this helm chart as an example: https://github.com/marlowl/geth-helm

Constraints: 
- 500gb Persistent Volume
- 800m RAM

**Comment by barbaraliau** [comment]
@yourbuddyconner this is answered or still working on?

**Comment by yourbuddyconner** [comment]
#wontdo, closing
