### ISSUE TITLE
Consider more explicit ownership solution

### ISSUE THREAD

**Issue by ErinHales** [celo-org/optics-monorepo#255]
The term `Owner` is very vague.  In our case, where we have multiple entities that have different roles/permissions, it is worth looking into solutions to make this more explicit.

Possible solution: https://github.com/celo-org/optics-monorepo/pull/226#discussion_r607798642

**Comment by prestwich** [comment]
Closing, as we have largely solved this issue. Owner now means `owner` in all cases. Explicit governance has changed to `governor`
