### ISSUE TITLE
Fix main's protected branch settings

### ISSUE THREAD

**Issue by ErinHales** [celo-org/optics-monorepo#261]
Currently, you have to have admin permissions in order to merge a branch into main.  Anyone should be able to merge into main as long as checks pass and there is 1 approving review and there are no conflicts with main.

Additionally, this means that I had to use my PAT for the merge bot so it could have the necessary permissions.  I would rather not do that...  Not super important right now, but we need to revisit this at some point.

**Comment by barbaraliau** [comment]
Reviewed the branch rules and it looks like you should be able to merge with 1 approving review, status checks pass, and no conflicts. It does require signed commits so users who don't have commit signing won't be able to have their code committed. Should update this in the README.
