### ISSUE TITLE
Make local/remote terminology consistent between contracts and tests

### ISSUE THREAD

**Issue by ltchang2019** [celo-org/optics-monorepo#293]
- in contracts, **`local`** refers to any chain's own domain (previously ownDomain) and **`remoteDomain`** now refers to domain of the origin chain (chain with home contract where messages originate)
- in tests, these terms are used in context of a single XApp, where **`local`** refers to chain with `XAppConnectionManager` setup and **`remotes`** refer to chains with replicas enrolled in the `XAppConnectionManager` that send messages to **`local`**

**Comment by ErinHales** [comment]
Ok, I think I see the confusion.  It's a matter of perspective.  When we're zoomed in on the `replica`, its local domain is the replica's domain and its remote domain is the home domain.  However, when we're zoomed out looking at `optics` as a whole, we should base our perspective off of `home`.  `deployOptics` would be the correct usage.
