### ISSUE TITLE
Think about spam

### ISSUE THREAD

**Issue by anna-carroll** [celo-org/optics-monorepo#344]
**problem**
- it's cheaper to send a message than it is to process it 
- anyone can send a bunch of messages to Optics to clog the system up
- we can't really solve this with governance because the GovernanceRouter uses Optics to send messages 

**ideas**
- cap number of messages in the queue?
- blacklist certain senders? (not sybil-resistant)

**Comment by prestwich** [comment]
I am increasingly of the opinion that we need to remove sequence numbers and give up the ordering guarantees in order to prevent spam
