### ISSUE TITLE
bug: solidity - invalid nonce

### ISSUE THREAD

**Issue by ErinHales** [celo-org/optics-monorepo#383]
![Screen Shot 2021-06-08 at 11 17 32 AM](https://user-images.githubusercontent.com/36751902/121230909-052ffc80-c84d-11eb-8f25-1dbfdb913778.png)

**Comment by prestwich** [comment]
@ErinHales I haven't seen this recently. If you haven't either, should we close as resolved with the big TS test refactor?

**Comment by prestwich** [comment]
closing as stale. seems to have been resolved
