### ISSUE TITLE
Implement Opentelemetry-jaeger tracing subscriber

### ISSUE THREAD

**Issue by yourbuddyconner** [celo-org/optics-monorepo#434]

**Comment by prestwich** [comment]
Okay I'm gonna push a small branch with some scaffolding for this

https://docs.rs/opentelemetry-jaeger/0.14.0/opentelemetry_jaeger/struct.PipelineBuilder.html

What I need to know next is what `with_` methods on the builder you'll need to call during setup. These will be config properties
