### ISSUE TITLE
Decide: How to Refactor Tracing Setup

### ISSUE THREAD

**Issue by yourbuddyconner** [celo-org/optics-monorepo#438]

**Comment by yourbuddyconner** [comment]
Our tracing implementation has to be refactored, especially to support forwarding `spans` to downstream consumers like Jaeger and Prometheus.

The goal of this ticket is to nail down exactly how we will do so. 

Ideas: 
- Implement subscriber registry using `tracing_subscriber` [crate](https://docs.rs/tracing-subscriber/0.2.19/tracing_subscriber/)
- Somehow integrate registry with `opentelemetry_jaeger` [crate](https://docs.rs/opentelemetry-jaeger/0.14.0/opentelemetry_jaeger/)
- Somehow integrate registry with `opentelemetry_prometheus` [crate](https://docs.rs/opentelemetry-prometheus/0.8.0/opentelemetry_prometheus/)

**Comment by prestwich** [comment]
Also relevant:
tracing_opentelemetry [crate](https://tracing.rs/tracing_opentelemetry/index.html)
