### ISSUE TITLE
test: Replica call recipient that isn't a contract

### ISSUE THREAD

**Issue by anna-carroll** [celo-org/optics-monorepo#440]

**Comment by prestwich** [comment]
More details:

we had a bug that would cause the replica to fail to process messages sent to a non-existent contract.

Add a test for this specific case, by sending a message to an address with no deployed contract. Use address `0x1234567890123456789012345678901234567890`

**Comment by ErinHales** [comment]
Steps for test:
1. Use opticsMessageSender for the sender and '0x1234567890123456789012345678901234567890' for the recipient address.
2. Format the message
3. Set the message to Pending (usually this is done during `prove` but we're going to shortcut it using `replica.setMessagePending`)
4. Check that it hasn’t been reverted: `await expect(replica.callStatic.process(opticsMessage)).to.not.be.reverted;`
