### ISSUE TITLE
BridgeRouter `requestDetails` of new token

### ISSUE THREAD

**Issue by anna-carroll** [celo-org/optics-monorepo#460]
- when a BridgeRouter deploys a new bridge token, it should send a `requestDetails` message to chain on which the token originates
- when a BridgeRouter receives a `requestDetails` message from a remote chain, it should 
   - ensure that the token contract in question originates on that chain
   - query the token contract for the name, symbol, & decimals of the token
   - send back an `updateDetails` message to the chain that requested details

**Comment by anna-carroll** [comment]
the challenge with updateDetails is that it's difficult for the origin chain to keep track of which chains have been sent the tokens. this approach gets messy quickly 

keeping track of which tokens have / haven't been seen on a given chain has to take place within the local BridgeRouter - we are already doing this with the behavior of the `reprToCanonical` mapping. 

when a local BridgeRouter encounters a new token, it can ping the originating chain to request an `updateDetails` message. there will be latency as there will need to be one round trip via Optics between the two chains, but this way we have a reasonably automated way of chains getting token information "automatically" once it is needed. combined with this https://github.com/celo-org/optics-monorepo/issues/459 cross-chain applications should have a reasonably smooth experience

**Comment by prestwich** [comment]
> * when a BridgeRouter receives a `requestDetails` message from a remote chain, it should

What is the behavior if it has no connection to that chain?
