### ISSUE TITLE
discussion: naming convention for bridge tokens

### ISSUE THREAD

**Issue by anna-carroll** [celo-org/optics-monorepo#461]
should there be some sort of naming convention for tokens sent via our bridge from a different origin chain?

example: UNI tokens sent from Ethereum to Celo; on the Celo chain, should their name be

1. `UNI` — same as on the origin chain
2. `eth.UNI` — to denote the token originates from Ethereum
3. `[domain].UNI` — prepend the Optics-addressed domain before the regular symbol
4. `bUNI`  or `bridgeUNI`— to denote that it arrived on this chain via a bridge
5. some other?

right now, the bridge behavior is option (1)

**Comment by anna-carroll** [comment]
my initial 2 sats -- feels like it's probably fine to stay with option (1)?

**Comment by prestwich** [comment]
option 2 requires introducing domain name strings to the chain somehow

fan of option 1 and 3

**Comment by critesjosh** [comment]
I like option 3 since it provides the most info about the token. If there are tokens with the same symbol from different chains, including the optics domain will help people know which is which.

Also, it can indicate to UI developers using the bridged tokens how they might want to display the token to users. If people are using `UNI` on Celo, it might be useful to display it as `ethUNI` for clarity.

**Comment by anna-carroll** [comment]
> If there are tokens with the same symbol from different chains, including the optics domain will help people know which is which.

this is true, but there are also tokens with the **same symbol on the same chain** - ultimately it's hard (impossible) to prevent naming collisions, even in a single-chain environment

**Comment by prestwich** [comment]
we pretty much have to assume that any naming convention we use there will be many maliciously-named impostor tokens

**Comment by anna-carroll** [comment]
> ultimately, you have to consult the `(domain, address)` to know the hard "truth"

this has inspired a new ticket: https://github.com/celo-org/optics-monorepo/issues/465

**Comment by anna-carroll** [comment]
Achieved rough emoji consensus on Slack to go with option #1 
![Screen Shot 2021-07-12 at 1.03.29 PM.png](https://images.zenhubusercontent.com/602936e3de0ee8159904c4c8/cd3c54f9-eadc-41df-ad52-7138adab82ee)
