### ISSUE TITLE
feature: upgradable BridgeToken implementation

### ISSUE THREAD

**Issue by anna-carroll** [celo-org/optics-monorepo#482]
- add ability to upgrade implementation of BridgeToken 
- use UpgradeBeacon pattern so all tokens are upgraded with one transaction

**Comment by prestwich** [comment]
blocked by #512

**Comment by prestwich** [comment]
1. TokenRegistry + BridgeRouter intializers need UBC address
2. TokenRegistry initializer deployc UB
3. change `_cloneTokenContract` to deploy UBP instead of standard proxy
