### ISSUE TITLE
add `domain` and `id` public variables to BridgeToken

### ISSUE THREAD

**Issue by anna-carroll** [celo-org/optics-monorepo#572]

**Comment by prestwich** [comment]
Can we do this in a way that doesn't add significant gas to the token deployment

**Comment by anna-carroll** [comment]
Closing ticket: xApp developers / people should never use the getter on the token contract to validate the (domain, ID) of a token - it's trivial for a malicious entity to dupe. the source of truth is the `BridgeRouter` contract, which already has a `getCanonicalAddress` getter function
