### ISSUE TITLE
emit Transfer-esque events from BridgeRouter when sending / handling token transfers

### ISSUE THREAD

**Issue by anna-carroll** [celo-org/optics-monorepo#573]
1. is the bridge router too large for this?
2. do we have enough gas in the tx for this?

Naming:
- TransferIn = handle transfer, TransferOut = send (possibly confusing)

**Comment by prestwich** [comment]
better:

- what is the officially-recommended way to identify a transfer event associated with a bridge message?
- how do we encode that official recommendation into an optics TS library?
- how do we produce an OpticsExplorer webapp to help with this?

**Comment by anna-carroll** [comment]
This issue was created to solve the problem of visibility / tracking of token transfers - and, more broadly, messages - on-chain. The problem is better-solved by off-chain tooling for the contracts; we will write a library which can be integrated to an API and/or CLI. this is tracked in the Epic "Contract Tooling"
