### ISSUE TITLE
docs: create agent deployment/staging doc

### ISSUE THREAD

**Issue by ErinHales** [celo-org/optics-monorepo#713]
Currently, there is not an easy way for an outside party to know what contract deploy the agents are pointed at.  We should maintain a document with this information.

TODO:
 - [x] create document
 - [x] list document in `Deploy Procedure` section of readme
 - [x] update document whenever agents are pointed at new deploy

DISCUSSION:
Since funds are locked up whenever the agents cease pointing at a contract deploy, we should think of some way to schedule/notify users of a redeploy

**Comment by yourbuddyconner** [comment]
See Agent Operations doc for details: https://github.com/celo-org/optics-monorepo/blob/main/docs/agents/agent-operations.md
