### ISSUE TITLE
bug: kathy isn't using message interval 

### ISSUE THREAD

**Issue by yourbuddyconner** [celo-org/optics-monorepo#748]
Interval is declared here: https://github.com/celo-org/optics-monorepo/blob/main/rust/agents/kathy/src/settings.rs#L48-L54

But never actually used here: https://github.com/celo-org/optics-monorepo/blob/main/rust/agents/kathy/src/kathy.rs

This causes her to bounce unnecessarily when transactions take some time to be processed.

**Comment by prestwich** [comment]
Seems like she's using it to set her duration which is slept after each dispatch

https://github.com/celo-org/optics-monorepo/blob/main/rust/agents/kathy/src/kathy.rs#L30
https://github.com/celo-org/optics-monorepo/blob/main/rust/agents/kathy/src/kathy.rs#L58
https://github.com/celo-org/optics-monorepo/blob/main/rust/agents/kathy/src/kathy.rs#L93
