### ISSUE TITLE
Move db logic from `optics-ethereum` to `optics-core`

### ISSUE THREAD

**Issue by prestwich** [celo-org/optics-monorepo#870]
- The chain-specific home currently keeps a DB and puts things into it.
- instead, this should be handled 1 layer up in `optics-core`. `Homes` enum 
- chain should be unaware of the DB

```
pub struct CachingHome {
    db: HomeDb
    home: Homes
}

// replace `impl Home for Homes`
impl Home for CachingHome {
    // for each function, check the DB first (if appropriate)
    // cache afterwards (if appropriate)
    // basically replicate the existing functionality in `EthereumHome`
}

```

**Comment by ltchang2019** [comment]
@prestwich So basically the goal here is that for every function that retrieves data (i.e. fetches from db), we want to implement that at the `Homes`/`CachingHome` level instead of at the chain-specific (e.g. `EthereumHome`) level? And while CachingHome may match on different `Homes` variants (e.g. Ethereum, Mock, etc), the db fetching functions simply call out to the db directly without matching?

**Comment by prestwich** [comment]
yes, exactly. The caching layer is not Ethereum-specific logic. It generalizes to all chains. So move it to the base instead of the chain

**Comment by ltchang2019** [comment]
If we're going to refactor to bring db logic out of chain-specific home interfaces, would it make sense to just completely remove query capabilities from the concept of a `Home/Homes` and leave it all to `HomeDB`? 

What I mean is that we just entirely separate command and query and that an agent accesses any home information directly from its `HomeDB`. The only reason we have query functions on the `home contract` interfaces is that we used to be able to call out directly to chain to retrieve info. Now that we have all home contract state is accessed locally through `HomeDB` I feel like queries should only go through `HomeDB`. Logically, it seems like functions like `signed_update_by_new_root` or `leaf_by_tree_index` don't need to go in two places (`HomeDB` and `Home`) and can just go in `HomeDB`.

**Comment by ltchang2019** [comment]
`CachingHome` also makes sense but I get the feeling it's going to get logically complicated with `HomeIndexer` filling `HomeDB` and `CachingHome` being a mix of command and quering `HomeDB`. Idk maybe I'm just overthinking...

**Comment by prestwich** [comment]
well we have to distinguish between state reads (not indexed locally) and events (indexed locally). But in general I like the direction you're going.

Because the current state isn't locally indexed, I think we want to keep a logical `Home` interface on top of the DB and chain connection

**Comment by ltchang2019** [comment]
Returning to this issue as we need to add db/indexing functionality to Replicas, I think the problem of separating db and chain-specific logic should probably be lower priority. Doing this before the standing up the watcher might take a bit of time. Here is the general design for the refactor but its quite a few parts which may take longer than we want:

![CachingHome](https://user-images.githubusercontent.com/32170738/137563449-1b16afdb-8155-402c-950c-f9b70de59a51.png)
