### ISSUE TITLE
Tracking Transactions

### ISSUE THREAD

**Issue by SurroundingArt64** [celo-org/optics-monorepo#943]
I also was able get the dispatch event in logs in Rinkeby: https://rinkeby.etherscan.io/tx/0xa802d5d2d80c0013416325f3e39bf60aab4da90198d3b8b8f4727c82656f884a#eventlog but didn't get anything on the remote **Kovan**

I had setup the following: https://github.com/SurroundingArt64/optics-nft-bridge

I think I might have setup the Routers incorrectly but I am not sure if that were the case:
https://github.com/SurroundingArt64/optics-nft-bridge/blob/7efc9e7b1b5abaaa193f17062f37d801cddf5052/contracts/nft/ERC721Router.sol#L51-L57

Also, I am using the staging contracts I found in this repo: https://github.com/SurroundingArt64/optics-nft-bridge/blob/master/utils/contracts.json

I have verified the routers as well. 

Rinkeby Router: [0x6097B933d7e032CE40e591270648C7330b73D111](https://rinkeby.etherscan.io/address/0x6097B933d7e032CE40e591270648C7330b73D111)
Kovan Router: [0xe44ff46d4EC1e2F868ee3653940Cfb286C3E5B0b](https://kovan.etherscan.io/address/0xe44ff46d4EC1e2F868ee3653940Cfb286C3E5B0b)

Can anyone help me here?

**Comment by afsoningo** [comment]
#945

**Comment by afsoningo** [comment]
# # #941 #939 #941 #940 #942 #940
